# -*- coding: utf-8 -*-
"""GAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_7P-blS9DhDX5r2cuqlWCfcLXjrs8nl
"""

# Load libraries

import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf
import keras
from keras.datasets import cifar10

#Load dataset

(trainX,_), (_, _) = cifar10.load_data()
trainX.shape

ix = np.random.randint(0, trainX.shape[0], 7*7)
X = trainX[ix]
plt.figure(figsize=(12,12))
for i in range(7 * 7):
  plt.subplot(7, 7, 1 + i)
  plt.axis('off')
  plt.imshow(X[i]/255)
plt.show()

def define_discriminator(in_shape=(32,32,3)):
	model = keras.models.Sequential()
	model.add(keras.layers.Conv2D(64, (3,3), strides=(1,1),padding='same', input_shape=in_shape))
	model.add(keras.layers.LeakyReLU(alpha=0.2))
	model.add(keras.layers.Conv2D(128, (3,3), strides=(2,2), padding='same'))
	model.add(keras.layers.LeakyReLU(alpha=0.2))
	model.add(keras.layers.Conv2D(128, (3,3), strides=(2,2), padding='same'))
	model.add(keras.layers.LeakyReLU(alpha=0.2))
	model.add(keras.layers.Conv2D(256, (3,3), strides=(2,2), padding='same'))
	model.add(keras.layers.LeakyReLU(alpha=0.2))
	model.add(keras.layers.Flatten())
	model.add(keras.layers.Dropout(0.4))
	model.add(keras.layers.Dense(2, activation='softmax'))
	opt = tf.keras.optimizers.Adam(lr=0.0002, beta_1=0.5)
	model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
	model.summary()
	return model

def define_generator(latent_dim):
	model = keras.models.Sequential()
	model.add(keras.layers.Dense(256 * 4 * 4, input_dim=latent_dim))
	model.add(keras.layers.LeakyReLU(alpha=0.2))
	model.add(keras.layers.Reshape((4, 4, 256)))
	model.add(keras.layers.Conv2DTranspose(128, (4,4), strides=(2,2), padding='same'))
	model.add(keras.layers.LeakyReLU(alpha=0.2))
	model.add(keras.layers.Conv2DTranspose(128, (4,4), strides=(2,2), padding='same'))
	model.add(keras.layers.LeakyReLU(alpha=0.2))
	model.add(keras.layers.Conv2DTranspose(128, (4,4), strides=(2,2), padding='same'))
	model.add(keras.layers.LeakyReLU(alpha=0.2))
	model.add(keras.layers.Conv2D(3, (3,3), strides=(1,1), activation='tanh', padding='same'))
	model.summary()
	return model

# Define GAN model

def define_gan(g_model, d_model):
	d_model.trainable = False
	model = keras.models.Sequential()
	model.add(g_model)
	model.add(d_model)
	model.summary()
	opt = tf.keras.optimizers.Adam(lr=0.0002, beta_1=0.5)
	model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
	return model

def load_real_samples():
	X = trainX[::10]
	X = X.astype('float32')
	X = (X - 127.5) / 127.5
	return X

def generate_real_samples(dataset, n_samples):
	ix = np.random.randint(0, dataset.shape[0], n_samples)
	X = dataset[ix]
	y = np.repeat(np.asarray([0, 1]).reshape(1, 2), n_samples, axis=0)
	return X, y

def generate_latent_points(latent_dim, n_samples):
	x_input = np.random.randn(latent_dim * n_samples)
	x_input = x_input.reshape(n_samples, latent_dim)
	return x_input

def generate_fake_samples(g_model, latent_dim, n_samples):
	x_input = generate_latent_points(latent_dim, n_samples)
	X = g_model.predict(x_input)
	y = np.repeat(np.asarray([1, 0]).reshape(1, 2), n_samples, axis=0)
	return X, y

def plot_generate(examples, n = 7):
  plt.figure(figsize=(12,12))
  examples = (examples + 1) / 2.0
  for i in range(n * n):
    plt.subplot(n, n, 1 + i)
    plt.axis('off')
    plt.imshow(examples[i])
  plt.show()
  plt.close()

def summarize_performance(epoch, g_model, d_model, dataset, latent_dim, n_samples=128):
  X_real, y_real = generate_real_samples(dataset, n_samples)
  _, acc_real = d_model.evaluate(X_real, y_real, verbose=0)
  x_fake, y_fake = generate_fake_samples(g_model, latent_dim, n_samples)
  _, acc_fake = d_model.evaluate(x_fake, y_fake, verbose=0)
  print(f'>Accuracy real: {acc_real*100}%, fake: {acc_fake*100}%')
  plot_generate(x_fake)
  filename = 'generator_model_%d.h5' % (epoch+1)
  g_model.save(filename)

# Train the Generator and Discriminator

def train(g_model, d_model, gan_model, dataset, latent_dim, n_epochs=500, n_batch=128): # Define the training model, n_epochs = 500, batch size = 128.
	bat_per_epo = int(dataset.shape[0] / n_batch)                                         # Calculate the number of batches in this cifar dataset
	half_batch = int(n_batch / 2)																													# Compute a half of batch
	for i in range(n_epochs): 																														# A loop of model training for n_epochs
		for j in range(bat_per_epo):																												# A loop of model training for bat_per_epo times in each epoch
			X_real, y_real = generate_real_samples(dataset, half_batch)												# Get randomly selected 'real' images of half batch
			d_loss1, _ = d_model.train_on_batch(X_real, y_real)																# Train discriminator model weights using real images
			X_fake, y_fake = generate_fake_samples(g_model, latent_dim, half_batch)						# Generate 'fake' images of half batch
			d_loss2, _ = d_model.train_on_batch(X_fake, y_fake)														  	# Train discriminator model weights using fake images
			X_gan = generate_latent_points(latent_dim, n_batch)																# Prepare input of a batch for the generator
			y_gan = np.repeat(np.asarray([0,1]).reshape(1,2), n_batch, axis=0)						  	# Define their labels as real images (i.e., [0, 1]) to generate more realistic images
			g_loss, _ = gan_model.train_on_batch(X_gan, y_gan)																# Train generator model weights using fake images
			print('>%d, %d/%d, d1=%.3f, d2=%.3f g=%.3f' % (i+1, j+1, bat_per_epo, d_loss1, d_loss2, g_loss))  			# Summarize loss on this batch
		if (i+1) % 10 == 0:																																	# Evaluate the model performance every 10 epochs
			summarize_performance(i, g_model, d_model, dataset, latent_dim)

# Model Training

dataset = load_real_samples()
dataset.shape

latent_dim = 100
d_model = define_discriminator()
g_model = define_generator(latent_dim)
gan_model = define_gan(g_model, d_model)
dataset = load_real_samples()
train(g_model, d_model, gan_model, dataset, latent_dim)

model = keras.models.load_model('generator_model_490.h5')
latent_points = generate_latent_points(100, 50)
X = model.predict(latent_points)
plot_generate(X, 7)